{% set version = '2.0-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ifultools
  version: {{ version|replace("-", "_") }}

source:
  fn: ifultools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ifultools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ifultools/ifultools_{{ version }}.tar.gz
  sha256: 22014c9f8ebe0ed5874c92ae83e06eeea6c7a5889fb2d63543b2e6a094ae625f

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-splus2r >=1.2_0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-splus2r >=1.2_0

test:
  commands:
    - $R -e "library('ifultools')"           # [not win]
    - "\"%R%\" -e \"library('ifultools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ifultools
  license: GPL-2
  summary: Insightful Research Tools.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
