{% set version = '2.0-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ifultools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ifultools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ifultools/ifultools_{{ version }}.tar.gz
  sha256: 72a8b20c4ff06bc2870af0f368a4bc8114a7126e174cf05554ab56f6d9da1310

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-splus2r >=1.2_0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-splus2r >=1.2_0

test:
  commands:
    - $R -e "library('ifultools')"           # [not win]
    - "\"%R%\" -e \"library('ifultools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ifultools
  license: GPL-2
  summary: Insightful Research Tools.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ifultools
# Title: Insightful Research Tools
# Version: 2.0-5
# Authors@R: person("William", "Constantine", email = "wlbconstan@gmail.com", role = c("cre", "aut"))
# Depends: R (>= 3.0.2)
# Imports: MASS, methods, splus2R (>= 1.2-0)
# Description: Insightful Research Tools.
# License: GPL-2
# Collate: it_mutils.R it_plot.R it_util.R it_calls.R package.R
# Repository: CRAN
# NeedsCompilation: yes
# Packaged: 2019-03-04 17:57:49 UTC; william
# Author: William Constantine [cre, aut]
# Maintainer: William Constantine <wlbconstan@gmail.com>
# Date/Publication: 2019-03-04 22:00:03 UTC
