# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IiVS+cAgCkklT+sEdvYPr/QQzfzvvLGkpVERgQUO7hJFlKMPK/T39Bx2ZSa7/uKIoWyKXYt+2oP16he5xgSVRew8Op9KUK4SOYP16eNSdc8Q4nTAqyIMz4AwgM8FWfq4sKMsREp4C6JSJLYMGfsupdKyLrvT+pG56TtLR5+dxoFXnf6Bzr1/kr41KWJLBrNTRgc/wdWtfeEK+QegcgnwmosvMJ20XSr26Cwm28AfmtoHZYD10IB1uYb3wR/R1jE3ybBdhwIPguXtf9HI8lFIvbD1qKI46quviirOqtD3PQdZCNJUMAo9M6fDsVoyqQRogqkVPMDq83nQ4sKvT65UmdnPL8q/5d/4IyhIPyYnnIVdraI/SmX3kPhWzRnyi6e+Un90PydBsilEH/yt/ZIzGusO612vUjL27s6aRoPzaN+sb6TWZdByCZDtPEXov8ZF94ZVznUQ2xTi/I6O+xICwjbW6qtSR584SnovxQ0YfI3EIc09j6GkKdCLNpaRYjBbMf26bIpW30mFF+hsutg4b2I6Co0e0fzwilswu2Hms/cHPtHEoLhg+hz24TGOAg+5lVcniNGguMWfzjYbxGNdozOcwceLlda4MpnYKMi+ngddcZbtbY45xOfdzwzyKAqQmmZSNP0B2xQ41+z2D5DcpeGmw32W901EFXtrgopEfgQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
