travis:
  secure:
    BINSTAR_TOKEN: pjEfUrtFkveBLDELqHmiBPJEcuQ3J24SOlyLYOUjFOVxOcJnlLYT5M++D5lxQxRaeNOvSwKBcipDuX2R3AcYebPslpvffvZaK9HHyKq+LzRbKkBS51hSFd+M3AcNzOgaKDnUS42sl7GFMuyqQqO01WwxRR3sN4ZysW+a4p/L21rqCqkLS+t2Pt6DhPr4hAbr2x9/Jb+kcbsHdDyBZKlri9WYWcC8pEr4rcbZOtmAEtDoik5lLGWDrYbqvoqd2adVuml+LVyfvsuKMatK1h+hZCoIjM+KGVdnvqVBi/FfgyVBAvh+ED9OvhMTRrbYiS6PaWOr75ENhXpJA9YsLjPetfx2td7npQlbKxtHqs75XIE2Kxfrp7Jb5cGm9jNXNL5YEJ2p8OYqeNg7LrnM1UfM98mxOpf1+4gipXYOnO8E9C4pRgfj4aGdlEub100eDU5y8J5N/OivBflDSuATH9TGG/qq8VCXrgXHjQYt6BGcYJbDJcyuLKIKZW0RR86/J6VPuA1pGXxYjwyGBxaYDEEKMZUvFE5XV/y/yX+yn2T/bZfxWSAGkdhJgCsDNme0pBMQ9zTJcsdnX65pOVNpZIlgyjnCvlt6vPxxnsfwv5c2pKN/bJfovdWWPF9HjuLsmeT22cmKdkozKp0J13lyX/RS5N3S7aJTjJUu+MPPWI+Mq7E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
