travis:
  secure:
    BINSTAR_TOKEN: e1o6Dw5SlscevtBvcii1n6pIJkSSaxl7e08X2IGnUldiBL6b2ZF2mygLvcNdOPMd8yAyrNWh9gp0WhqshuJvGnNqGkwgaPkkoioy5XWxvGbAqYHAlP0FzV7l71CXCU8INBGz+M3DGhRuQLCPcLQXQJDYtiHe0l35G4xjA0E+Y2pVeKzVl7O1zXZ/vTQ4BiZbrl7zYZas5p/QRwYq4i/IJSQRMktcHoGEY4sfjli3mLf52wuXdv4/E//BAfdVDGJGVKWIVRcrcpbe5mv2YTybMnLYh0F9tkUNrZmlOWZmub2WC4C0qRutvNEL56bml0Hjtvk3DIG0mzSQSXONAyxnJ8nYJ4frtKbGSU2tqzGVlGjOdXZUP2B2obCsSIXELGkj+dOTDTbP0FWlnL3tzIzYlMw9QSJTRK3ZVGA6+ZlNyhM/3hspaz6XwuB2T7QP6LIOiE3/Di46Evc4/DtKOxAFrVPvScZOQ6tonCUxkWfuW50C2EuM9cSJe5xJpa1cWGH/WiCIBKRF6pMIaayFIB1JfKQWSl5JSzvBfR74nem7LA3OdlRCfPGGKbYaMgWPBBRO9Pe+c5Ga53p6uXADIIK3luWCJ1jfSv1pQlHXHBGUTiukMl0Ct4WdpqOhPqpHQzY9xVsfJ+hK8+wX0Q8YoD0o0IsW0QdD8XynxNA4E0tNgO4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
