travis:
  secure:
    BINSTAR_TOKEN: KRmVsCH0KKoeCjvYed5w1wKD5v/vkTGpvZsKwYy6s259Wvh1hvlM15nRhi2kY24tI1q7SECOMSCiXPhuTFIt9YITTpLfYt3YqlVG+2rq3k8z0lCE5SowGTEHYWc9V+Fch8vW24T7plA3G4+AIg1f2iownTcZBQAN0+buegZhseRt0FgYxGLsM5AqgVzaAF2sDL+o7klKAaNbHsU1YZdYLolRV62eRQmqHqOXdkASzR9vJVUmvdfHxzPw6caR/dLMg80gCWPsGM2RZ03j4cLzIKeS2uexLzzRNAZEEIZCFKmZdu2yrLkD7HFngKBM46xRIUeww8svOIQ+9Y3R3JwJqucPx5VvH1+1x0Kgek3vjEm/+oJcoTPTD4ISIcIUmegUkxgtxTROyhtf3tpnnOQSkyNm+gXUBA8Xv6ihmO3nTX2ViyX08wB1tnNU+Olr3Xex6yewyRAfQb3xzMmcethZeWb8pOfndsYoMgZj3Yg/OpklO1sFsrpBGrl+1/pJHHkUXKlp5Syxt35JL0yqwFzU53Xrk/sCypgKt7hHl1PWzNv9N8wbKF1IziCktdI2PDdHPMjh2G4JhcqWfjtQl54K0+f9t/saRUSLUuCXazjEfQTzkv8JLjEeuEUxTl5CiexJJV4eZQdn9iHFKkP4walsoXa0kYCurtl2Z16e+MBx4Jg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
