travis:
  secure:
    BINSTAR_TOKEN: IiVS+cAgCkklT+sEdvYPr/QQzfzvvLGkpVERgQUO7hJFlKMPK/T39Bx2ZSa7/uKIoWyKXYt+2oP16he5xgSVRew8Op9KUK4SOYP16eNSdc8Q4nTAqyIMz4AwgM8FWfq4sKMsREp4C6JSJLYMGfsupdKyLrvT+pG56TtLR5+dxoFXnf6Bzr1/kr41KWJLBrNTRgc/wdWtfeEK+QegcgnwmosvMJ20XSr26Cwm28AfmtoHZYD10IB1uYb3wR/R1jE3ybBdhwIPguXtf9HI8lFIvbD1qKI46quviirOqtD3PQdZCNJUMAo9M6fDsVoyqQRogqkVPMDq83nQ4sKvT65UmdnPL8q/5d/4IyhIPyYnnIVdraI/SmX3kPhWzRnyi6e+Un90PydBsilEH/yt/ZIzGusO612vUjL27s6aRoPzaN+sb6TWZdByCZDtPEXov8ZF94ZVznUQ2xTi/I6O+xICwjbW6qtSR584SnovxQ0YfI3EIc09j6GkKdCLNpaRYjBbMf26bIpW30mFF+hsutg4b2I6Co0e0fzwilswu2Hms/cHPtHEoLhg+hz24TGOAg+5lVcniNGguMWfzjYbxGNdozOcwceLlda4MpnYKMi+ngddcZbtbY45xOfdzwzyKAqQmmZSNP0B2xQ41+z2D5DcpeGmw32W901EFXtrgopEfgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
